# Generated by Django 2.2 on 2020-03-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_project_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='destination',
            field=models.CharField(default='here', max_length=45),
            preserve_default=False,
        ),
    ]
